---
ci:
  autofix_commit_msg: "fix: Apply pre-commit.ci auto fixes"
  autoupdate_commit_msg: "chore: Update pre-commit hooks"
  autoupdate_schedule: monthly
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 9.0.2
    hooks:
      - id: isort
        pass_filenames: false
        args: [flypse]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.19.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff-check
        args: [--fix, --select, "F401"]
        name: ruff pycln
      - id: ruff-check
        pass_filenames: false
        args: [flypse]
      - id: ruff-format
        pass_filenames: false
        args: [flypse]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.4.0
    hooks:
      - id: mypy
        pass_filenames: false
        args: [flypse]

exclude: "examples/.*"
